setwd("\\Rcourse")
saleData = read.csv("Data.csv")
plot(saleData)
head(saleData)
simpleModel = lm(Sales.l~Adv.cost.k,saleData)
summary(simpleModel)
dim(saleData)
Model = read.csv("new_data.csv")
pred = predict.lm(simpleModel,newdata = Model)
print(pred)
class(pred)
pred = as.data.frame(pred)
Model = cbind(Model,pred)
View(Model)
qqnorm(simpleModel$residuals)
shapiro.test(simpleModel$residuals)
